### ISSUE TITLE
A help page pops up each time you open it. How can I close it?

### ISSUE THREAD

**Issue by lxitdn** [KeeTrayTOTP/KeeTrayTOTP#42] opened 2019-10-05 14:41 UTC
A help page pops up each time you open it. How can I close it?

**Comment by Sanaki** [comment] 2019-10-06 01:13
Duplicate of #18.

**Comment by dannoe** [comment] 2020-04-06 06:37
I'm going to close this issue. 
If you still have problems with it, please comment this issue or open a new one.

**Closed by dannoe** 2020-04-06 06:37 UTC
Labels: duplicate
