### ISSUE TITLE
Help Menu Opens on KeePass Start

### ISSUE THREAD

**Issue by RobertKlohr** [KeeTrayTOTP/KeeTrayTOTP#18] opened 2018-05-11 21:47 UTC
The help menu, with the original plugin title Tray TOTP, launches every time KeePass starts. While not a bad idea if this happens on the first launch after the plugin is loaded to have this happen every time is unnecessary and requires manually closing the dialog box every time KeePass is loaded.
![keetraytotp help](https://user-images.githubusercontent.com/39203582/39948292-28651d5a-552a-11e8-975e-ab14d3d56d12.png)

**Comment by robinvanpoppel** [comment] 2018-05-14 06:13
@RjKGitHub: I looked at the code involved as I can not reproduce this issue. It looks at a flag called "firstinstall_shown" and then decides whether to show the help window. From what I know this flag should be saved to KeePass.config.xml

My config file (%userprofile%\AppData\Roaming\KeePass) contains this under <Custom>. Can you check whether your file contains this flag? 

```
<Item>
	<Key>firstinstall_shown</Key>
	<Value>true</Value>
</Item>
```

Relevant code
https://github.com/victor-rds/KeeTrayTOTP/blob/578ef06eb1399b6de1b4a4482ae1424fe6ee38c1/TrayTOTP_Plugin.cs#L283-L298

**Comment by robinvanpoppel** [comment] 2018-05-31 19:39
@RjKGitHub Did you manage to solve this issue yourself?

**Comment by robinvanpoppel** [comment] 2018-06-18 12:17
Closing due to inactivity.

**Comment by RjKGitHub** [comment] 2018-06-20 04:00
Sorry I missed your post and only noticed it when the plugin was updated to 0.94.

Yes my configuration file (%userprofile%\AppData\Roaming\KeePass\KeePass.config.xml) does contain this item at the end of the file.

What I did notice based on look at this was that I had another KeePass.config.xml file in the installation directory that I have used for years to set some defaults for other family members that use the computer.  Since we all run as non-admin users this file never gets updated.  What KeePass does is read in this file and the one in the local profile to determine the applied settings.

It seems that this plugin executes it's "show help on first install" after the configuration file in the install directory is loaded but before the configuration file in the user profile is loaded.

**Comment by robinvanpoppel** [comment] 2020-02-09 09:01
@RjKGitHub, from what I can find this plugin asks Keepass for its configuration values and should not make any effort to determine in which config the settings are stored. I was not able to reproduce this.

As a workaround you can add the `firstinstall_shown` with value `true` in the Keepass.config.xml in the installation directory to prevent this from popping up.

**Comment by RjKGitHub** [comment] 2020-02-12 06:45
I actually did what you just suggested over a year ago. ;-)

I do think that I figured out what was happening and why.

What I did not realize though until I just re-read this thread and the the information on how the [configuration files are loaded and saved](https://keepass.info/help/base/configuration.html#tech) is that in my case the setting `PreferUserConfiguration` not present in the configuration file, as I manually copied that config file from a portable installation, which means it defaults to `false`.

With `PreferUserConfiguration` being `false` KeePass loads the settings from config file located in %ProgramFiles(x86)%.  When it comes time to save the configuration settings it will try to the write back to the same file and fail due to lack of permission.  The fallback behavior is for KeePass to then write the settings, including the one for your plugin, to the config file in %appdata%.

This is why your plugin the settings were in %appdata% and not in %ProgramFiles(x86)% and why the plugin never saw them when it loaded.

The is definitely an edge case that I don't think you can compensate for in your (or any) plugin and at best you might want to note in somewhere in case someone else ends up with a similar configuration.

**Comment by dannoe** [comment] 2020-04-06 06:48
KeePass itself should probably inform the user, when it can not save the config.
We could implement a detection for this, but I think this is the wrong place.

**Comment by robinvanpoppel** [comment] 2020-05-11 15:13
Closing this for now as the underlying issue should not be fixed within this plugin. If this happens more frequently and people cannot find this issue as the underlying cause we can add it to a FAQ section.

**Closed by robinvanpoppel** 2020-05-11 15:13 UTC
Labels: keepass-problem
