### ISSUE TITLE
Add an entry that displays the code

### ISSUE THREAD

**Issue by alexis26** [KeeTrayTOTP/KeeTrayTOTP#188] opened 2020-09-19 07:37 UTC
hello,
it would be good to add an entry in the menu allowing ' to display the code (and the remaining time) '.
(it would even be nice if it was in another window, so we could focus on another window while seeing the code in the background while typing).

I have 2 use cases where you can't copy/paste and I have to write the code (so I have to be able to display it): 
-when it asked on my phone, I would like to be able to display the code easily on the computer, to be able to type it.
-when I use a virtual phone on the computer, some apps refuse ctrl-v (and keyboard) for OTP and you have to type it manually (using their virtual keyboard)
(I asked them the question and they even told me that it was part of their security specifications not to trust the clipboard, so they block all interactions between the app and the clipboard).
Thank you

**Comment by dannoe** [comment] 2020-09-19 07:42
somewhat a duplicate of: https://github.com/KeeTrayTOTP/KeeTrayTOTP/issues/186

**Closed** 2020-09-24 19:46 UTC
Labels: duplicate, enhancement
